---
version: "3.9"

services:
  nzb:
    extends:
      file: src/nzb/sabnzbd.yaml
      service: nzb
  torrent:
    extends:
      file: src/torrent/qbittorrent.yaml
      service: torrent
  books:
    extends:
      file: src/books/readarr.yaml
      service: books
  music:
    extends:
      file: src/music/lidarr.yaml
      service: music
  movies:
    extends:
      file: src/movies/radarr.yaml
      service: movies
  tv:
    extends:
      file: src/tv/sonarr.yaml
      service: tv
  subs:
    extends:
      file: src/subs/bazarr.yaml
      service: subs
  trackers:
    extends:
      file: src/trackers/jackett.yaml
      service: trackers

  request:
    extends:
      file: src/request/overseerr.yaml
      service: request
networks:
  proxy-net:
    external: true
  xcode-net:
    external: false