---
version: "3.9"

services: 
  music:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: music
    env_file:
      - .env
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./music:/music
    ports:
      - 30086:8686
    networks:
      - proxy-net
    restart: unless-stopped