version: "3.9"

services: 
  movies:
    image: lscr.io/linuxserver/radarr:latest
    container_name: movies
    env_file:
      - .env
    volumes:
      - ./backups:/config/backups
      - ./config:/config
      - ./downloads:/downloads
      - ./movies:/movies
    ports:
      - 30082:7878
    networks:
      - proxy-net
    restart: unless-stopped